# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3466f82d4692ab2ffc1b88883584fea38a51817d2cc21eba2e22ef86475218dfd59b0a2ba701766b187dd3a97a7d6176dad7d14b0df0c050762a28b2c311b6c8

test:
  secret_key_base: fad417b44f65d1c14a43b1312094a3793b45f7208c187d8dec7ce7d4af23f56f34811b8e9339248c4c5a2339d09e6f226f8788a9906ca063a66cc75ed4f643cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
